<?php

	$block = Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('fdmsconnect_error');	

	$html = Mage::helper('fdmsconnect')->getCustomerMessage($block, Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId()), Mage::getModel('fdmsconnect/fdmsconnect')->getCollection()->addFieldToFilter('order_id', Mage::getSingleton('checkout/session')->getLastRealOrderId())->getFirstItem());

	echo $html;
	
?>